CREATE TABLE IF NOT EXISTS accounts
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid varchar(40),
    iban varchar(40),
    balance BIGINT,
    person_id   varchar(40), FOREIGN KEY (person_id) REFERENCES persons(uid),
    created_at timestamp,
    updated_at timestamp
);
